### ISSUE TITLE
How to use call recording feature 

### ISSUE THREAD

**Issue by Jagdeep-Sing** [plivo/plivo-websdk-2.0-example#17]
There is no option for recording in UI
But in code, recording feature is there
How to use that ?

**Comment by Jagdeep-Sing** [comment]
THANK YOU FOR YOUR QUICK SUPPORT PLIVO.

**Comment by tutysathish** [comment]
Hi Jagdepp,

Can you guide me to implement a call recording feature using Plivo Web SDK?

Is it possible to achieve using web SDK or we may need to use API's
